### ISSUE TITLE
Would you consider registering HSM.jl on JuliaHub?

### ISSUE THREAD

**Issue by g-gundam** [AndrewWasHere/HSM.jl#1]
This is one of the nicer state machine libraries I've come across for Julia.  I think it would be beneficial if people were able to find it when searching for state machines on JuliaHub.

https://julialang.org/contribute/developing_package/#step_5_register_your_package

**Comment by AndrewWasHere** [comment]
Thanks! When I get a chance, I will register it.

**Comment by AndrewWasHere** [comment]
Registered. Haven't triggered JuliaRegistrator yet because there are some changes to make first.
