### ISSUE TITLE
Minor bugs in example/thermometer-notebook.jl

### ISSUE THREAD

**Issue by g-gundam** [AndrewWasHere/HSM.jl#5]
I had to make two little changes to make the example notebook work for me again.

```diff
@@ -142,7 +144,7 @@ struct UnitsEvent <: HSM.AbstractHsmEvent
 end

 # ╔═╡ 5e3ff2ba-5deb-464e-b087-a2bbec22c254
-struct TemperatureEvent <:AbstractHsmEvent
+struct TemperatureEvent <: HSM.AbstractHsmEvent
        temperature::Float32
 end

```

and

```diff
@@ -412,7 +414,7 @@ new_temp
 # ╔═╡ 925fdbca-f263-4d28-9bbf-ab23a5810471
 with_terminal() do
        with_logger(logger) do
-               handle_event!(thermometer_state_machine, TemperatureEvent(new_temp))
+               HSM.handle_event!(thermometer_state_machine, TemperatureEvent(new_temp))
                println("display: $(thermometer.display)")
                println("temperature: $(thermometer.temperature)")
        end
```

I don't feel comfortable sending a pull request for this one, because my Pluto instance changed so many other things when it installed the dependencies for the notebook.  I think it'd be less intrusive if you made these changes yourself.

**Comment by AndrewWasHere** [comment]
It wasn't less intrusive. Probably because that notebook was ~2 years old. Now works with Julia 1.11 and whatever version Pluto is as of today.
