### ISSUE TITLE
Your state machine code in action

### ISSUE THREAD

**Issue by g-gundam** [AndrewWasHere/HSM.jl#6]
## This is not a bug.

This is your state machine code helping me manage the lifecycle of a trade in my backtesting (and eventually live trading) system.

![image](https://github.com/user-attachments/assets/b06dd6dc-8bb7-45cf-be0f-9303a5ff6862)

Here is what the state machine looks like.

![image](https://github.com/user-attachments/assets/487a1dc2-32f6-4c69-941a-ca6b9a89c63d)

Wishing you a belated Merry Christmas, and thanks again for publishing your library.  It has been very helpful to me.

PS:  Here's a [static export of the notebook](https://g-gundam.github.io/notebooks/01.hma-4h-improvements/).

**Comment by AndrewWasHere** [comment]
Nice! I'd never thought about trading being a state machine. Makes sense.

Happy New Year!
